name: binance_dart
description: A simple Dart client to the Binance API.
version: 0.0.1
homepage: https://github.com/fhassis/binance-dart

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  http: ^0.13.4
  crypto: ^3.0.1
  dio: ^4.0.1

dev_dependencies:
  lints: ^2.0.0
